### ISSUE TITLE
791211/810722: Typo on line 396 in dung.mud

### ISSUE THREAD

**Issue by heasm66** [heasm66/mdlzork#20]
"fovnder" should be "founder".

**Comment by eriktorbjorn** [comment]
The Fortran version makes the same change, but I can't help wonder if it was deliberate. There was a time when the letter V was used instead of U. See https://www.dictionary.com/e/theletteru/ for some information about this. I also found this example in the [Statue of John Carroll](https://en.wikipedia.org/wiki/Statue_of_John_Carroll) Wikipedia article:

![fovnder](https://user-images.githubusercontent.com/601765/232245665-634f3134-bd16-4d99-bc72-78086b287120.jpg)

Another example would be Dave Lebling's "The Lurking Horror":

```
>WEST
You enter the freezing, biting cold of the blizzard.

Mass. Ave.
This is the main entrance to the campus buildings. Blinding snow obscures the
stately Grecian columns and rounded dome to the east. You can barely make out
the inscription on the pediment (which reads "George Vnderwood Edwards, Fovnder;
P. David Lebling, Architect; Russell Lieblich, Sound Engineer"). West across
Massachusetts Avenue are other buildings, but you can't see them.
```

**Comment by larsbrinkhoff** [comment]
I share @eriktorbjorn's reservations about this.

**Comment by larsbrinkhoff** [comment]
Maybe consider that U and V are not close on a keyboard, and typed with different hands (if touch typing).

**Comment by heasm66** [comment]
Valid comment. I'll reopen this issue and change it back.

**Comment by gmenounos** [comment]
Pretty sure "fovnder" was intentional:
![image](https://github.com/heasm66/mdlzork/assets/8294827/7deddc96-8d87-437e-b6e1-57a532bb6e9b)
